/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AdjustCreditsDto,
  CreateCreditPackageDto,
  CreditBalanceResponseDto,
  CreditPackage,
  GetCreditLedgerParams,
  GetCreditTransactionsParams,
  PaginatedLedgerResponseDto,
  PaginatedTransactionResponseDto,
  PurchaseCreditsDto,
} from '../models';

import { axiosInstance } from '../custom-instance';
import type { ErrorType, BodyType } from '../custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Admin only
 * @summary Create credit package
 */
export const createCreditPackage = (
  createCreditPackageDto: BodyType<CreateCreditPackageDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<CreditPackage>(
    {
      url: `/api/credits/packages`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCreditPackageDto,
      signal,
    },
    options
  );
};

export const getCreateCreditPackageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCreditPackage>>,
    TError,
    { data: BodyType<CreateCreditPackageDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCreditPackage>>,
  TError,
  { data: BodyType<CreateCreditPackageDto> },
  TContext
> => {
  const mutationKey = ['createCreditPackage'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCreditPackage>>,
    { data: BodyType<CreateCreditPackageDto> }
  > = (props) => {
    const { data } = props ?? {};

    return createCreditPackage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCreditPackageMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCreditPackage>>
>;
export type CreateCreditPackageMutationBody = BodyType<CreateCreditPackageDto>;
export type CreateCreditPackageMutationError = ErrorType<void>;

/**
 * @summary Create credit package
 */
export const useCreateCreditPackage = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCreditPackage>>,
      TError,
      { data: BodyType<CreateCreditPackageDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createCreditPackage>>,
  TError,
  { data: BodyType<CreateCreditPackageDto> },
  TContext
> => {
  const mutationOptions = getCreateCreditPackageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Public endpoint - no authentication required
 * @summary Get all active credit packages
 */
export const getCreditPackages = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<CreditPackage[]>(
    { url: `/api/credits/packages`, method: 'GET', signal },
    options
  );
};

export const getGetCreditPackagesQueryKey = () => {
  return [`/api/credits/packages`] as const;
};

export const getGetCreditPackagesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCreditPackages>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackages>>, TError, TData>>;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCreditPackagesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCreditPackages>>> = ({ signal }) =>
    getCreditPackages(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCreditPackages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCreditPackagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCreditPackages>>
>;
export type GetCreditPackagesQueryError = ErrorType<unknown>;

export function useGetCreditPackages<
  TData = Awaited<ReturnType<typeof getCreditPackages>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackages>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditPackages>>,
          TError,
          Awaited<ReturnType<typeof getCreditPackages>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditPackages<
  TData = Awaited<ReturnType<typeof getCreditPackages>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackages>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditPackages>>,
          TError,
          Awaited<ReturnType<typeof getCreditPackages>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditPackages<
  TData = Awaited<ReturnType<typeof getCreditPackages>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackages>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all active credit packages
 */

export function useGetCreditPackages<
  TData = Awaited<ReturnType<typeof getCreditPackages>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackages>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCreditPackagesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return query;
}

/**
 * Public endpoint - no authentication required
 * @summary Get credit package by ID
 */
export const getCreditPackage = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<CreditPackage>(
    { url: `/api/credits/packages/${id}`, method: 'GET', signal },
    options
  );
};

export const getGetCreditPackageQueryKey = (id?: string) => {
  return [`/api/credits/packages/${id}`] as const;
};

export const getGetCreditPackageQueryOptions = <
  TData = Awaited<ReturnType<typeof getCreditPackage>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackage>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCreditPackageQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCreditPackage>>> = ({ signal }) =>
    getCreditPackage(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCreditPackage>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCreditPackageQueryResult = NonNullable<Awaited<ReturnType<typeof getCreditPackage>>>;
export type GetCreditPackageQueryError = ErrorType<void>;

export function useGetCreditPackage<
  TData = Awaited<ReturnType<typeof getCreditPackage>>,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackage>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditPackage>>,
          TError,
          Awaited<ReturnType<typeof getCreditPackage>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditPackage<
  TData = Awaited<ReturnType<typeof getCreditPackage>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackage>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditPackage>>,
          TError,
          Awaited<ReturnType<typeof getCreditPackage>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditPackage<
  TData = Awaited<ReturnType<typeof getCreditPackage>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackage>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get credit package by ID
 */

export function useGetCreditPackage<
  TData = Awaited<ReturnType<typeof getCreditPackage>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditPackage>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCreditPackageQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return query;
}

/**
 * @summary Update credit package (Admin only)
 */
export const updateCreditPackage = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<void>({ url: `/api/credits/packages/${id}`, method: 'PATCH' }, options);
};

export const getUpdateCreditPackageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCreditPackage>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCreditPackage>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['updateCreditPackage'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCreditPackage>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return updateCreditPackage(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCreditPackageMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCreditPackage>>
>;

export type UpdateCreditPackageMutationError = ErrorType<void>;

/**
 * @summary Update credit package (Admin only)
 */
export const useUpdateCreditPackage = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCreditPackage>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateCreditPackage>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getUpdateCreditPackageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete credit package (Admin only)
 */
export const deleteCreditPackage = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<void>({ url: `/api/credits/packages/${id}`, method: 'DELETE' }, options);
};

export const getDeleteCreditPackageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCreditPackage>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCreditPackage>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteCreditPackage'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCreditPackage>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCreditPackage(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCreditPackageMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCreditPackage>>
>;

export type DeleteCreditPackageMutationError = ErrorType<void>;

/**
 * @summary Delete credit package (Admin only)
 */
export const useDeleteCreditPackage = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCreditPackage>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCreditPackage>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteCreditPackageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Purchase credits
 */
export const purchaseCredits = (
  purchaseCreditsDto: BodyType<PurchaseCreditsDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<void>(
    {
      url: `/api/credits/purchase`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: purchaseCreditsDto,
      signal,
    },
    options
  );
};

export const getPurchaseCreditsMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purchaseCredits>>,
    TError,
    { data: BodyType<PurchaseCreditsDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof purchaseCredits>>,
  TError,
  { data: BodyType<PurchaseCreditsDto> },
  TContext
> => {
  const mutationKey = ['purchaseCredits'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purchaseCredits>>,
    { data: BodyType<PurchaseCreditsDto> }
  > = (props) => {
    const { data } = props ?? {};

    return purchaseCredits(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PurchaseCreditsMutationResult = NonNullable<
  Awaited<ReturnType<typeof purchaseCredits>>
>;
export type PurchaseCreditsMutationBody = BodyType<PurchaseCreditsDto>;
export type PurchaseCreditsMutationError = ErrorType<void>;

/**
 * @summary Purchase credits
 */
export const usePurchaseCredits = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof purchaseCredits>>,
      TError,
      { data: BodyType<PurchaseCreditsDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof purchaseCredits>>,
  TError,
  { data: BodyType<PurchaseCreditsDto> },
  TContext
> => {
  const mutationOptions = getPurchaseCreditsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get current credit balance and summary
 * @summary Get credit balance
 */
export const getCreditBalance = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<CreditBalanceResponseDto>(
    { url: `/api/credits/balance`, method: 'GET', signal },
    options
  );
};

export const getGetCreditBalanceQueryKey = () => {
  return [`/api/credits/balance`] as const;
};

export const getGetCreditBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getCreditBalance>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditBalance>>, TError, TData>>;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCreditBalanceQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCreditBalance>>> = ({ signal }) =>
    getCreditBalance(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCreditBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCreditBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof getCreditBalance>>>;
export type GetCreditBalanceQueryError = ErrorType<void>;

export function useGetCreditBalance<
  TData = Awaited<ReturnType<typeof getCreditBalance>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditBalance>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditBalance>>,
          TError,
          Awaited<ReturnType<typeof getCreditBalance>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditBalance<
  TData = Awaited<ReturnType<typeof getCreditBalance>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditBalance>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditBalance>>,
          TError,
          Awaited<ReturnType<typeof getCreditBalance>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditBalance<
  TData = Awaited<ReturnType<typeof getCreditBalance>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditBalance>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get credit balance
 */

export function useGetCreditBalance<
  TData = Awaited<ReturnType<typeof getCreditBalance>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditBalance>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCreditBalanceQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return query;
}

/**
 * Get paginated credit ledger entries (audit trail)
 * @summary Get credit ledger history
 */
export const getCreditLedger = (
  params?: GetCreditLedgerParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<PaginatedLedgerResponseDto>(
    { url: `/api/credits/ledger`, method: 'GET', params, signal },
    options
  );
};

export const getGetCreditLedgerQueryKey = (params?: GetCreditLedgerParams) => {
  return [`/api/credits/ledger`, ...(params ? [params] : [])] as const;
};

export const getGetCreditLedgerQueryOptions = <
  TData = Awaited<ReturnType<typeof getCreditLedger>>,
  TError = ErrorType<void>,
>(
  params?: GetCreditLedgerParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditLedger>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCreditLedgerQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCreditLedger>>> = ({ signal }) =>
    getCreditLedger(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCreditLedger>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCreditLedgerQueryResult = NonNullable<Awaited<ReturnType<typeof getCreditLedger>>>;
export type GetCreditLedgerQueryError = ErrorType<void>;

export function useGetCreditLedger<
  TData = Awaited<ReturnType<typeof getCreditLedger>>,
  TError = ErrorType<void>,
>(
  params: undefined | GetCreditLedgerParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditLedger>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditLedger>>,
          TError,
          Awaited<ReturnType<typeof getCreditLedger>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditLedger<
  TData = Awaited<ReturnType<typeof getCreditLedger>>,
  TError = ErrorType<void>,
>(
  params?: GetCreditLedgerParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditLedger>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditLedger>>,
          TError,
          Awaited<ReturnType<typeof getCreditLedger>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditLedger<
  TData = Awaited<ReturnType<typeof getCreditLedger>>,
  TError = ErrorType<void>,
>(
  params?: GetCreditLedgerParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditLedger>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get credit ledger history
 */

export function useGetCreditLedger<
  TData = Awaited<ReturnType<typeof getCreditLedger>>,
  TError = ErrorType<void>,
>(
  params?: GetCreditLedgerParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCreditLedger>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCreditLedgerQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return query;
}

/**
 * Get paginated credit purchase transactions
 * @summary Get credit transaction history
 */
export const getCreditTransactions = (
  params?: GetCreditTransactionsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<PaginatedTransactionResponseDto>(
    { url: `/api/credits/transactions`, method: 'GET', params, signal },
    options
  );
};

export const getGetCreditTransactionsQueryKey = (params?: GetCreditTransactionsParams) => {
  return [`/api/credits/transactions`, ...(params ? [params] : [])] as const;
};

export const getGetCreditTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCreditTransactions>>,
  TError = ErrorType<void>,
>(
  params?: GetCreditTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCreditTransactions>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCreditTransactionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCreditTransactions>>> = ({ signal }) =>
    getCreditTransactions(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCreditTransactions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCreditTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCreditTransactions>>
>;
export type GetCreditTransactionsQueryError = ErrorType<void>;

export function useGetCreditTransactions<
  TData = Awaited<ReturnType<typeof getCreditTransactions>>,
  TError = ErrorType<void>,
>(
  params: undefined | GetCreditTransactionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCreditTransactions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditTransactions>>,
          TError,
          Awaited<ReturnType<typeof getCreditTransactions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditTransactions<
  TData = Awaited<ReturnType<typeof getCreditTransactions>>,
  TError = ErrorType<void>,
>(
  params?: GetCreditTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCreditTransactions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCreditTransactions>>,
          TError,
          Awaited<ReturnType<typeof getCreditTransactions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCreditTransactions<
  TData = Awaited<ReturnType<typeof getCreditTransactions>>,
  TError = ErrorType<void>,
>(
  params?: GetCreditTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCreditTransactions>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get credit transaction history
 */

export function useGetCreditTransactions<
  TData = Awaited<ReturnType<typeof getCreditTransactions>>,
  TError = ErrorType<void>,
>(
  params?: GetCreditTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCreditTransactions>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCreditTransactionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return query;
}

/**
 * @summary Adjust user credits (Admin only)
 */
export const adjustCredits = (
  adjustCreditsDto: BodyType<AdjustCreditsDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<void | void>(
    {
      url: `/api/credits/admin/adjust`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: adjustCreditsDto,
      signal,
    },
    options
  );
};

export const getAdjustCreditsMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adjustCredits>>,
    TError,
    { data: BodyType<AdjustCreditsDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adjustCredits>>,
  TError,
  { data: BodyType<AdjustCreditsDto> },
  TContext
> => {
  const mutationKey = ['adjustCredits'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adjustCredits>>,
    { data: BodyType<AdjustCreditsDto> }
  > = (props) => {
    const { data } = props ?? {};

    return adjustCredits(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdjustCreditsMutationResult = NonNullable<Awaited<ReturnType<typeof adjustCredits>>>;
export type AdjustCreditsMutationBody = BodyType<AdjustCreditsDto>;
export type AdjustCreditsMutationError = ErrorType<void>;

/**
 * @summary Adjust user credits (Admin only)
 */
export const useAdjustCredits = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adjustCredits>>,
      TError,
      { data: BodyType<AdjustCreditsDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof adjustCredits>>,
  TError,
  { data: BodyType<AdjustCreditsDto> },
  TContext
> => {
  const mutationOptions = getAdjustCreditsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
