/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CostEstimationDto,
  DetectThemeDto,
  EstimateCostParams,
  GenerateContentDto,
  GenerationResponseDto,
  MediaToTextDto,
  RewriteLyricsDto,
  ScenarioFromThemeDto,
  SuggestScenarioDto,
  SyncKaraokeBody,
  TranscribeAudioBody,
} from '../models';

import { axiosInstance } from '../custom-instance';
import type { ErrorType, BodyType } from '../custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Generate text content using Google GenAI. Credits will be deducted based on token usage.
 * @summary Generate content using AI
 */
export const generateContent = (
  generateContentDto: BodyType<GenerateContentDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/generate`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: generateContentDto,
      signal,
    },
    options
  );
};

export const getGenerateContentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateContent>>,
    TError,
    { data: BodyType<GenerateContentDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateContent>>,
  TError,
  { data: BodyType<GenerateContentDto> },
  TContext
> => {
  const mutationKey = ['generateContent'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateContent>>,
    { data: BodyType<GenerateContentDto> }
  > = (props) => {
    const { data } = props ?? {};

    return generateContent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateContent>>
>;
export type GenerateContentMutationBody = BodyType<GenerateContentDto>;
export type GenerateContentMutationError = ErrorType<void>;

/**
 * @summary Generate content using AI
 */
export const useGenerateContent = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateContent>>,
      TError,
      { data: BodyType<GenerateContentDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof generateContent>>,
  TError,
  { data: BodyType<GenerateContentDto> },
  TContext
> => {
  const mutationOptions = getGenerateContentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get an estimate of credits needed for a given prompt
 * @summary Estimate credit cost for generation
 */
export const estimateCost = (
  params: EstimateCostParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<CostEstimationDto>(
    { url: `/api/genai/cost-estimate`, method: 'GET', params, signal },
    options
  );
};

export const getEstimateCostQueryKey = (params?: EstimateCostParams) => {
  return [`/api/genai/cost-estimate`, ...(params ? [params] : [])] as const;
};

export const getEstimateCostQueryOptions = <
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEstimateCostQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof estimateCost>>> = ({ signal }) =>
    estimateCost(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof estimateCost>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EstimateCostQueryResult = NonNullable<Awaited<ReturnType<typeof estimateCost>>>;
export type EstimateCostQueryError = ErrorType<void>;

export function useEstimateCost<
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof estimateCost>>,
          TError,
          Awaited<ReturnType<typeof estimateCost>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEstimateCost<
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof estimateCost>>,
          TError,
          Awaited<ReturnType<typeof estimateCost>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEstimateCost<
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Estimate credit cost for generation
 */

export function useEstimateCost<
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEstimateCostQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return query;
}

/**
 * Generate Vietnamese lyrics from original text. Pass structured config; the server builds the prompt internally. Credits will be deducted based on token usage.
 * @summary Rewrite song lyrics using AI
 */
export const rewriteLyrics = (
  rewriteLyricsDto: BodyType<RewriteLyricsDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/rewrite-lyrics`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: rewriteLyricsDto,
      signal,
    },
    options
  );
};

export const getRewriteLyricsMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rewriteLyrics>>,
    TError,
    { data: BodyType<RewriteLyricsDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rewriteLyrics>>,
  TError,
  { data: BodyType<RewriteLyricsDto> },
  TContext
> => {
  const mutationKey = ['rewriteLyrics'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rewriteLyrics>>,
    { data: BodyType<RewriteLyricsDto> }
  > = (props) => {
    const { data } = props ?? {};

    return rewriteLyrics(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RewriteLyricsMutationResult = NonNullable<Awaited<ReturnType<typeof rewriteLyrics>>>;
export type RewriteLyricsMutationBody = BodyType<RewriteLyricsDto>;
export type RewriteLyricsMutationError = ErrorType<void>;

/**
 * @summary Rewrite song lyrics using AI
 */
export const useRewriteLyrics = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rewriteLyrics>>,
      TError,
      { data: BodyType<RewriteLyricsDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof rewriteLyrics>>,
  TError,
  { data: BodyType<RewriteLyricsDto> },
  TContext
> => {
  const mutationOptions = getRewriteLyricsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Analyse lyrics and return a theme/style name and story description. Credits will be deducted based on token usage.
 * @summary Detect theme and story from lyrics
 */
export const detectTheme = (
  detectThemeDto: BodyType<DetectThemeDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/detect-theme`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: detectThemeDto,
      signal,
    },
    options
  );
};

export const getDetectThemeMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof detectTheme>>,
    TError,
    { data: BodyType<DetectThemeDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof detectTheme>>,
  TError,
  { data: BodyType<DetectThemeDto> },
  TContext
> => {
  const mutationKey = ['detectTheme'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof detectTheme>>,
    { data: BodyType<DetectThemeDto> }
  > = (props) => {
    const { data } = props ?? {};

    return detectTheme(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DetectThemeMutationResult = NonNullable<Awaited<ReturnType<typeof detectTheme>>>;
export type DetectThemeMutationBody = BodyType<DetectThemeDto>;
export type DetectThemeMutationError = ErrorType<void>;

/**
 * @summary Detect theme and story from lyrics
 */
export const useDetectTheme = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof detectTheme>>,
      TError,
      { data: BodyType<DetectThemeDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof detectTheme>>,
  TError,
  { data: BodyType<DetectThemeDto> },
  TContext
> => {
  const mutationOptions = getDetectThemeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Given a theme/style name, generate a short scenario description for song lyric writing. Credits will be deducted based on token usage.
 * @summary Generate a scenario based on music theme
 */
export const scenarioFromTheme = (
  scenarioFromThemeDto: BodyType<ScenarioFromThemeDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/scenario-from-theme`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: scenarioFromThemeDto,
      signal,
    },
    options
  );
};

export const getScenarioFromThemeMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof scenarioFromTheme>>,
    TError,
    { data: BodyType<ScenarioFromThemeDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof scenarioFromTheme>>,
  TError,
  { data: BodyType<ScenarioFromThemeDto> },
  TContext
> => {
  const mutationKey = ['scenarioFromTheme'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof scenarioFromTheme>>,
    { data: BodyType<ScenarioFromThemeDto> }
  > = (props) => {
    const { data } = props ?? {};

    return scenarioFromTheme(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ScenarioFromThemeMutationResult = NonNullable<
  Awaited<ReturnType<typeof scenarioFromTheme>>
>;
export type ScenarioFromThemeMutationBody = BodyType<ScenarioFromThemeDto>;
export type ScenarioFromThemeMutationError = ErrorType<void>;

/**
 * @summary Generate a scenario based on music theme
 */
export const useScenarioFromTheme = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof scenarioFromTheme>>,
      TError,
      { data: BodyType<ScenarioFromThemeDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof scenarioFromTheme>>,
  TError,
  { data: BodyType<ScenarioFromThemeDto> },
  TContext
> => {
  const mutationOptions = getScenarioFromThemeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Propose creative scenarios/ideas based on user prompt. Credits will be deducted based on token usage.
 * @summary Suggest AI generation scenarios
 */
export const suggestScenario = (
  suggestScenarioDto: BodyType<SuggestScenarioDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/suggest-scenario`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: suggestScenarioDto,
      signal,
    },
    options
  );
};

export const getSuggestScenarioMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof suggestScenario>>,
    TError,
    { data: BodyType<SuggestScenarioDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof suggestScenario>>,
  TError,
  { data: BodyType<SuggestScenarioDto> },
  TContext
> => {
  const mutationKey = ['suggestScenario'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof suggestScenario>>,
    { data: BodyType<SuggestScenarioDto> }
  > = (props) => {
    const { data } = props ?? {};

    return suggestScenario(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SuggestScenarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof suggestScenario>>
>;
export type SuggestScenarioMutationBody = BodyType<SuggestScenarioDto>;
export type SuggestScenarioMutationError = ErrorType<void>;

/**
 * @summary Suggest AI generation scenarios
 */
export const useSuggestScenario = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof suggestScenario>>,
      TError,
      { data: BodyType<SuggestScenarioDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof suggestScenario>>,
  TError,
  { data: BodyType<SuggestScenarioDto> },
  TContext
> => {
  const mutationOptions = getSuggestScenarioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Upload an audio or video file and transcribe lyrics using Gemini Flash. mode=karaoke: returns ALL repeated sections in order (for karaoke sync). mode=lyrics (default): returns unique song structure without repetition (for lyric rewriting).
 * @summary Transcribe audio/video to text using Gemini Flash multimodal
 */
export const transcribeAudio = (
  transcribeAudioBody: BodyType<TranscribeAudioBody>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  formData.append(`file`, transcribeAudioBody.file);
  if (transcribeAudioBody.language !== undefined) {
    formData.append(`language`, transcribeAudioBody.language);
  }
  if (transcribeAudioBody.mode !== undefined) {
    formData.append(`mode`, transcribeAudioBody.mode);
  }

  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/transcribe`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options
  );
};

export const getTranscribeAudioMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof transcribeAudio>>,
    TError,
    { data: BodyType<TranscribeAudioBody> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof transcribeAudio>>,
  TError,
  { data: BodyType<TranscribeAudioBody> },
  TContext
> => {
  const mutationKey = ['transcribeAudio'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof transcribeAudio>>,
    { data: BodyType<TranscribeAudioBody> }
  > = (props) => {
    const { data } = props ?? {};

    return transcribeAudio(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TranscribeAudioMutationResult = NonNullable<
  Awaited<ReturnType<typeof transcribeAudio>>
>;
export type TranscribeAudioMutationBody = BodyType<TranscribeAudioBody>;
export type TranscribeAudioMutationError = ErrorType<void>;

/**
 * @summary Transcribe audio/video to text using Gemini Flash multimodal
 */
export const useTranscribeAudio = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof transcribeAudio>>,
      TError,
      { data: BodyType<TranscribeAudioBody> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof transcribeAudio>>,
  TError,
  { data: BodyType<TranscribeAudioBody> },
  TContext
> => {
  const mutationOptions = getTranscribeAudioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Upload audio file with raw lyrics text. Whisper CTC alignment maps each lyric line to actual sung timestamps, then assigns per-word timings via text-similarity anchoring. Dynamic cost based on lyric word count.
 * @summary Sync lyrics with audio using AI
 */
export const syncKaraoke = (
  syncKaraokeBody: BodyType<SyncKaraokeBody>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  formData.append(`file`, syncKaraokeBody.file);
  formData.append(`rawLyrics`, syncKaraokeBody.rawLyrics);

  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/sync-karaoke`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options
  );
};

export const getSyncKaraokeMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof syncKaraoke>>,
    TError,
    { data: BodyType<SyncKaraokeBody> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof syncKaraoke>>,
  TError,
  { data: BodyType<SyncKaraokeBody> },
  TContext
> => {
  const mutationKey = ['syncKaraoke'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof syncKaraoke>>,
    { data: BodyType<SyncKaraokeBody> }
  > = (props) => {
    const { data } = props ?? {};

    return syncKaraoke(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SyncKaraokeMutationResult = NonNullable<Awaited<ReturnType<typeof syncKaraoke>>>;
export type SyncKaraokeMutationBody = BodyType<SyncKaraokeBody>;
export type SyncKaraokeMutationError = ErrorType<void>;

/**
 * @summary Sync lyrics with audio using AI
 */
export const useSyncKaraoke = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof syncKaraoke>>,
      TError,
      { data: BodyType<SyncKaraokeBody> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof syncKaraoke>>,
  TError,
  { data: BodyType<SyncKaraokeBody> },
  TContext
> => {
  const mutationOptions = getSyncKaraokeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Convert audio or video file to text using AI. Supports transcription with custom prompts. Credits will be deducted based on token usage.
 * @summary Convert audio/video to text
 */
export const mediaToText = (
  mediaToTextDto: BodyType<MediaToTextDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/media-to-text`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: mediaToTextDto,
      signal,
    },
    options
  );
};

export const getMediaToTextMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mediaToText>>,
    TError,
    { data: BodyType<MediaToTextDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mediaToText>>,
  TError,
  { data: BodyType<MediaToTextDto> },
  TContext
> => {
  const mutationKey = ['mediaToText'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mediaToText>>,
    { data: BodyType<MediaToTextDto> }
  > = (props) => {
    const { data } = props ?? {};

    return mediaToText(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MediaToTextMutationResult = NonNullable<Awaited<ReturnType<typeof mediaToText>>>;
export type MediaToTextMutationBody = BodyType<MediaToTextDto>;
export type MediaToTextMutationError = ErrorType<void>;

/**
 * @summary Convert audio/video to text
 */
export const useMediaToText = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof mediaToText>>,
      TError,
      { data: BodyType<MediaToTextDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof mediaToText>>,
  TError,
  { data: BodyType<MediaToTextDto> },
  TContext
> => {
  const mutationOptions = getMediaToTextMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
