/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  ConfirmPaymentDto,
  ConfirmPaymentResponseDto,
  CreatePaymentLinkDto,
  PaymentLinkResponseDto,
} from '../models';

import { axiosInstance } from '../custom-instance';
import type { ErrorType, BodyType } from '../custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Tạo payment link để mua gói credits qua PayOS (VietQR, ngân hàng nội địa)
 * @summary Tạo link thanh toán PayOS
 */
export const createPaymentLink = (
  createPaymentLinkDto: BodyType<CreatePaymentLinkDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<PaymentLinkResponseDto>(
    {
      url: `/api/payment/create-link`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPaymentLinkDto,
      signal,
    },
    options
  );
};

export const getCreatePaymentLinkMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPaymentLink>>,
    TError,
    { data: BodyType<CreatePaymentLinkDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPaymentLink>>,
  TError,
  { data: BodyType<CreatePaymentLinkDto> },
  TContext
> => {
  const mutationKey = ['createPaymentLink'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPaymentLink>>,
    { data: BodyType<CreatePaymentLinkDto> }
  > = (props) => {
    const { data } = props ?? {};

    return createPaymentLink(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePaymentLinkMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPaymentLink>>
>;
export type CreatePaymentLinkMutationBody = BodyType<CreatePaymentLinkDto>;
export type CreatePaymentLinkMutationError = ErrorType<void>;

/**
 * @summary Tạo link thanh toán PayOS
 */
export const useCreatePaymentLink = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPaymentLink>>,
      TError,
      { data: BodyType<CreatePaymentLinkDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createPaymentLink>>,
  TError,
  { data: BodyType<CreatePaymentLinkDto> },
  TContext
> => {
  const mutationOptions = getCreatePaymentLinkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Gọi sau khi user được redirect về từ PayOS với status PAID
 * @summary Xác nhận thanh toán và cộng credits
 */
export const confirmPayment = (
  confirmPaymentDto: BodyType<ConfirmPaymentDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<ConfirmPaymentResponseDto>(
    {
      url: `/api/payment/confirm`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: confirmPaymentDto,
      signal,
    },
    options
  );
};

export const getConfirmPaymentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof confirmPayment>>,
    TError,
    { data: BodyType<ConfirmPaymentDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof confirmPayment>>,
  TError,
  { data: BodyType<ConfirmPaymentDto> },
  TContext
> => {
  const mutationKey = ['confirmPayment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof confirmPayment>>,
    { data: BodyType<ConfirmPaymentDto> }
  > = (props) => {
    const { data } = props ?? {};

    return confirmPayment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConfirmPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof confirmPayment>>>;
export type ConfirmPaymentMutationBody = BodyType<ConfirmPaymentDto>;
export type ConfirmPaymentMutationError = ErrorType<void>;

/**
 * @summary Xác nhận thanh toán và cộng credits
 */
export const useConfirmPayment = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof confirmPayment>>,
      TError,
      { data: BodyType<ConfirmPaymentDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof confirmPayment>>,
  TError,
  { data: BodyType<ConfirmPaymentDto> },
  TContext
> => {
  const mutationOptions = getConfirmPaymentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Nhận webhook từ PayOS khi thanh toán thành công
 * @summary PayOS webhook endpoint
 */
export const payosWebhook = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<void | void>(
    { url: `/api/payment/webhook`, method: 'POST', signal },
    options
  );
};

export const getPayosWebhookMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof payosWebhook>>, TError, void, TContext>;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof payosWebhook>>, TError, void, TContext> => {
  const mutationKey = ['payosWebhook'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof payosWebhook>>, void> = () => {
    return payosWebhook(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PayosWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof payosWebhook>>>;

export type PayosWebhookMutationError = ErrorType<unknown>;

/**
 * @summary PayOS webhook endpoint
 */
export const usePayosWebhook = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof payosWebhook>>, TError, void, TContext>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof payosWebhook>>, TError, void, TContext> => {
  const mutationOptions = getPayosWebhookMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
