/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDto } from './userResponseDto';

export interface AuthResponseDto {
  /** JWT access token (expires in 10 minutes) */
  accessToken: string;
  /** JWT refresh token (expires in 1 day) */
  refreshToken: string;
  /** User information */
  user: UserResponseDto;
}
