/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type CreateCreditPackageDto = {
  /** Package name */
  name: string;
  /**
   * Number of credits in the package
   * @minimum 1
   */
  credits: number;
  /**
   * Package price in USD
   * @minimum 0
   */
  price: number;
  /**
   * Validity period in days
   * @minimum 1
   */
  validityDays?: number;
  /** Package description */
  description?: string;
  /** Whether the package is active */
  isActive?: boolean;
};
