/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * Additional transaction metadata
 * @nullable
 */
export type CreditTransactionMetadata = { [key: string]: unknown } | null;
