/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export interface CreditBalanceResponseDto {
  /** Total credits ever purchased */
  totalCredits: number;
  /** Total credits used */
  usedCredits: number;
  /** Currently available credits */
  availableCredits: number;
  /** Credits that have expired */
  expiredCredits: number;
  /** Credits expiring in the next 7 days */
  creditsExpiringSoon: number;
}
