/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { CreditPackage } from './creditPackage';
import type { CreditTransactionMetadata } from './creditTransactionMetadata';

export interface CreditTransaction {
  /** Transaction unique identifier */
  id: string;
  /** User who made the purchase */
  user: User;
  /** Credit package purchased */
  package: CreditPackage;
  /** Number of credits purchased */
  creditsPurchased: number;
  /** Transaction amount in USD */
  amount: number;
  /** Transaction status */
  status: string;
  /** Payment method used */
  paymentMethod?: string;
  /** Payment gateway transaction ID */
  paymentTransactionId?: string;
  /** Purchase timestamp */
  purchaseDate: string;
  /** Credits expiration timestamp */
  expiresAt: string;
  /**
   * Additional transaction metadata
   * @nullable
   */
  metadata?: CreditTransactionMetadata;
}
