/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { GenerationDataDto } from './generationDataDto';

export interface GenerationResponseDto {
  /** Success message */
  message: string;
  /** Generation data */
  data: GenerationDataDto;
}
