/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export interface GenerateContentDto {
  /** The prompt for AI content generation */
  prompt: string;
  /**
   * Maximum number of tokens to generate
   * @minimum 1
   * @maximum 2048
   */
  maxTokens?: number;
  /** AI model to use */
  model?: string;
}
