/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { CreditTransaction } from './creditTransaction';
import type { GetCreditTransactions200Meta } from './getCreditTransactions200Meta';

export type GetCreditTransactions200 = {
  data?: CreditTransaction[];
  meta?: GetCreditTransactions200Meta;
};
