/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { GetUsers200Meta } from './getUsers200Meta';

export type GetUsers200 = {
  data?: User[];
  meta?: GetUsers200Meta;
};
