/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { MediaToTextDtoMediaType } from './mediaToTextDtoMediaType';

export type MediaToTextDto = {
  /** URL of the audio/video file to convert to text */
  mediaUrl: string;
  /** Media type (audio or video) */
  mediaType: MediaToTextDtoMediaType;
  /** Additional prompt to guide AI processing (e.g., "Transcribe this song lyrics", "Extract dialogue from this video") */
  prompt?: string;
  /** Language of the media */
  language?: string;
  /** AI model to use */
  model?: string;
};
