/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * Media type (audio or video)
 */
export type MediaToTextDtoMediaType =
  (typeof MediaToTextDtoMediaType)[keyof typeof MediaToTextDtoMediaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaToTextDtoMediaType = {
  audio: 'audio',
  video: 'video',
} as const;
