/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { PaginationMeta } from './paginationMeta';

export type PaginatedUsersResponseDto = {
  /** List of users */
  data: User[];
  /** Pagination metadata */
  meta: PaginationMeta;
};
