/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * User role
 */
export type Role = (typeof RoleEnum)[keyof typeof RoleEnum];

export const RoleEnum = {
  user: 'user',
  admin: 'admin',
} as const;
