/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoRole } from './updateUserDtoRole';

export interface UpdateUserDto {
  /** User full name */
  fullName?: string;
  /** Whether the user account is active */
  isActive?: boolean;
  /** User role */
  role?: UpdateUserDtoRole;
}
