/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type UploadDataDto = {
  /** Public URL of the uploaded file */
  url: string;
  /** Original file name */
  fileName: string;
  /** Content type of the file */
  contentType: string;
  /** File size in bytes */
  size: number;
};
