/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type UploadDataDto = {
  /** Gemini Files API URI - use this directly as mediaUrl in media-to-text */
  uri: string;
  /** File ID in Gemini Files API (use this to delete the file) */
  fileId: string;
  /** Original file name */
  fileName: string;
  /** Content type of the file */
  contentType: string;
  /** File size in bytes */
  size: number;
};
