/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type UserResponseDto = {
  /** User ID */
  id: string;
  /** User email */
  email: string;
  /** User full name */
  fullName: string;
  /** User role */
  role: string;
};
