/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { AdjustCreditsDtoMetadata } from './adjustCreditsDtoMetadata';

export type AdjustCreditsDto = {
  /** User ID to adjust credits for */
  userId: string;
  /** Amount to adjust (positive to add, negative to subtract) */
  amount: number;
  /** Reason for adjustment */
  description: string;
  /** Additional metadata */
  metadata?: AdjustCreditsDtoMetadata;
};
