/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type ChangePasswordDto = {
  /** Current password */
  currentPassword: string;
  /**
   * New password (min 8 chars)
   * @minLength 8
   */
  newPassword: string;
};
