/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type ConfirmPaymentDto = {
  /** Credit package ID to confirm payment for */
  packageId: string;
  /**
   * PayOS order code returned from createPaymentLink
   * @minimum 1
   */
  orderCode: number;
};
