/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { Role } from './role';

export type CreateUserDto = {
  /** User email address */
  email: string;
  /**
   * User password (minimum 6 characters)
   * @minLength 6
   */
  password: string;
  /** User full name */
  fullName?: string;
  /** User role */
  role?: Role;
};
