/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { CreditTransaction } from './creditTransaction';

export type CreditPackage = {
  /** Package unique identifier */
  id: string;
  /** Package name */
  name: string;
  /** Number of credits in the package */
  credits: number;
  /** Package price in USD */
  price: number;
  /** Validity period in days */
  validityDays: number;
  /** Package availability status */
  isActive: boolean;
  /** Package description */
  description?: string;
  /** Package creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  transactions: CreditTransaction[];
};
