/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { CreditTransactionType } from './creditTransactionType';
import type { CreditLedgerMetadata } from './creditLedgerMetadata';

export type CreditLedger = {
  /** Ledger entry unique identifier */
  id: string;
  /** User associated with this ledger entry */
  user: User;
  /** Transaction type */
  type: CreditTransactionType;
  /** Credits deducted */
  debit: number;
  /** Credits added */
  credit: number;
  /** Balance after this transaction */
  balance: number;
  /** Transaction description */
  description?: string;
  /**
   * Additional metadata
   * @nullable
   */
  metadata?: CreditLedgerMetadata;
  /** Reference ID to related transaction */
  referenceId?: string;
  /** Entry creation timestamp */
  createdAt: string;
  /** Credit expiration timestamp */
  expiresAt?: string;
  /** Whether credits have expired */
  isExpired: boolean;
};
