/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * Transaction type
 */
export type CreditTransactionType =
  (typeof CreditTransactionType)[keyof typeof CreditTransactionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreditTransactionType = {
  PURCHASE: 'PURCHASE',
  USAGE: 'USAGE',
  EXPIRATION: 'EXPIRATION',
  REFUND: 'REFUND',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
} as const;
