/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type DetectThemeDto = {
  /**
   * Original lyrics text to analyse for theme and story
   * @minLength 1
   */
  lyrics: string;
};
