/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type GenerateNeonThemeDto = {
  /**
   * Mood/style description to generate a neon visualizer theme
   * @minLength 1
   * @maxLength 200
   */
  mood: string;
};
