/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type GenerationDataDto = {
  /** Generated text content */
  generatedText: string;
  /** Credits used for generation */
  creditsUsed: number;
  /** Remaining credits after generation */
  remainingCredits: number;
};
