/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { MediaToTextDtoMediaType } from './mediaToTextDtoMediaType';

export type MediaToTextDto = {
  /** URI of the file from Gemini Files API (from the uri field in upload response) */
  mediaUrl: string;
  /** Media type (audio or video) */
  mediaType: MediaToTextDtoMediaType;
  /** MIME type of the file. If omitted, defaults to audio/mpeg for audio and video/mp4 for video. */
  mimeType?: string;
  /** Additional prompt to guide AI processing (e.g., "Transcribe this song lyrics") */
  prompt?: string;
  /** Language of the media content */
  language?: string;
};
