/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { PackageBreakdownDto } from './packageBreakdownDto';

export type MyPackagesResponseDto = {
  /** Available credits balance */
  availableCredits: number;
  /** Total credits ever purchased */
  totalCredits: number;
  /** Total credits used */
  usedCredits: number;
  /** Total credits expired */
  expiredCredits: number;
  /** Credits expiring within 7 days */
  creditsExpiringSoon: number;
  packages: PackageBreakdownDto[];
};
