/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type PackageBreakdownDto = {
  /** Ledger entry ID */
  ledgerId: string;
  /** Package name */
  packageName: string;
  /** Purchase date */
  purchasedAt: string;
  /**
   * Expiry date
   * @nullable
   */
  expiresAt: string | null;
  /** Total credits in this package */
  creditsTotal: number;
  /** Credits used from this package */
  creditsUsed: number;
  /** Credits remaining */
  creditsRemaining: number;
  /** Whether this package has expired */
  isExpired: boolean;
  /**
   * Days until expiry, null if no expiry or already expired
   * @nullable
   */
  daysUntilExpiry: number | null;
};
