/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { CreditLedger } from './creditLedger';
import type { PaginationMetaDto } from './paginationMetaDto';

export type PaginatedLedgerResponseDto = {
  /** List of credit ledger entries */
  data: CreditLedger[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
};
