/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type PurchaseCreditsDto = {
  /** Credit package ID to purchase */
  packageId: string;
  /** Payment method used */
  paymentMethod?: string;
  /** External payment transaction ID */
  paymentTransactionId?: string;
};
