/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type RefreshTokenDto = {
  /** Refresh token to exchange for new access token */
  refreshToken: string;
};
