/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

export type RegisterDto = {
  /** User email address */
  email: string;
  /**
   * Password: 8–64 characters, must contain at least one letter and one number
   * @minLength 8
   * @maxLength 64
   * @pattern /^(?=.*[A-Za-z])(?=.*\d).+$/
   */
  password: string;
  /**
   * User full name
   * @maxLength 100
   */
  fullName?: string;
};
