/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * Singer gender — affects pronoun and tone choices
 */
export type RewriteLyricsDtoGender =
  (typeof RewriteLyricsDtoGender)[keyof typeof RewriteLyricsDtoGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RewriteLyricsDtoGender = {
  male: 'male',
  female: 'female',
} as const;
