/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { RewriteLyricsDtoSourceLanguage } from './rewriteLyricsDtoSourceLanguage';
import type { RewriteLyricsDtoGender } from './rewriteLyricsDtoGender';
import type { RewriteLyricsDtoMode } from './rewriteLyricsDtoMode';

export type RewriteLyricsDto = {
  /**
   * Original lyrics text to rewrite
   * @minLength 1
   */
  originalText: string;
  /** Source language of the original lyrics */
  sourceLanguage?: RewriteLyricsDtoSourceLanguage;
  /** Music theme / style for the rewritten lyrics */
  theme?: string;
  /** Story/scenario description to guide the rewriting */
  storyDescription?: string;
  /** Singer gender — affects pronoun and tone choices */
  gender?: RewriteLyricsDtoGender;
  /** "strict" = Đồng điệu 100% (match syllable count + tones). "creative" = Sáng tác tự do (free creative flow) */
  mode?: RewriteLyricsDtoMode;
  /** Use the thinking model (higher quality, slower & more expensive) */
  useThinking?: boolean;
};
