/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * "strict" = Đồng điệu 100% (match syllable count + tones). "creative" = Sáng tác tự do (free creative flow)
 */
export type RewriteLyricsDtoMode = (typeof RewriteLyricsDtoModeEnum)[keyof typeof RewriteLyricsDtoModeEnum];

export const RewriteLyricsDtoModeEnum = {
  strict: 'strict',
  creative: 'creative',
} as const;
