/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * Source language of the original lyrics
 */
export type RewriteLyricsDtoSourceLanguage =
  (typeof RewriteLyricsDtoSourceLanguage)[keyof typeof RewriteLyricsDtoSourceLanguage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RewriteLyricsDtoSourceLanguage = {
  auto: 'auto',
  vi: 'vi',
  zh: 'zh',
  ko: 'ko',
  en: 'en',
  ja: 'ja',
} as const;
