/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { SuggestScenarioDtoScenarioType } from './suggestScenarioDtoScenarioType';

export type SuggestScenarioDto = {
  /** Brief description of your needs */
  prompt: string;
  /** Type of scenario to suggest */
  scenarioType?: SuggestScenarioDtoScenarioType;
  /** Number of suggestions to receive */
  numberOfSuggestions?: number;
};
