/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * Type of scenario to suggest
 */
export type SuggestScenarioDtoScenarioType =
  (typeof SuggestScenarioDtoScenarioType)[keyof typeof SuggestScenarioDtoScenarioType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SuggestScenarioDtoScenarioType = {
  music_lyrics: 'music_lyrics',
  story_writing: 'story_writing',
  marketing: 'marketing',
  creative_writing: 'creative_writing',
  general: 'general',
} as const;
