/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */

/**
 * lyrics = unique structure for rewriting; karaoke = full with all repetitions
 */
export type TranscribeAudioBodyMode =
  (typeof TranscribeAudioBodyMode)[keyof typeof TranscribeAudioBodyMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TranscribeAudioBodyMode = {
  lyrics: 'lyrics',
  karaoke: 'karaoke',
} as const;
