/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import type { Role } from './role';

export type User = {
  /** User unique identifier */
  id: string;
  /** User email address */
  email: string;
  /** User full name */
  fullName?: string;
  /** User role */
  role: Role;
  /** User account status */
  isActive: boolean;
  /** Account creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  password: string;
};
