import { TextStyle } from '../types/karaoke';

export const FONTS = ['Plus Jakarta Sans', 'Cormorant Garamond'];

export const DEFAULT_STYLE: TextStyle = {
  fontFamily: 'Plus Jakarta Sans',
  fontSize: 16,
  letterSpacing: 1,
  initialColor: '#94a3b8',
  activeColor: '#ffffff',
  strokeColor: '#000000',
  strokeWidth: 0,
  shadowBlur: 15,
  shadowColor: '#000000',
  shadowOffsetX: 0,
  shadowOffsetY: 4,
  positionX: 50,
  positionY: 85,
  allCaps: false,
  introTitle: 'Tên Bài Hát',
  introArtist: 'Ca Sĩ',
  textAnimation: 'classic',
  ktvFillType: 'flat',
  vfxType: 'stars',
  vfxIntensity: 40,
  vfxSpeed: 1.0,
  vfxColor: '#f59e0b',
  bgPulseIntensity: 50,
  visualizerType: 'mirror',
  iconType: 'none',
  iconSize: 24,
  iconPosX: 10,
  iconPosY: 10,
  iconOpacity: 0.9,
  logoUrl: null,
  logoSize: 80,
  logoOpacity: 0.8,
  logoPosition: 'top-right',
};
