/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CostEstimationDto,
  EstimateCostParams,
  GenerateContentDto,
  GenerationResponseDto,
  MediaToTextDto,
  SuggestScenarioDto,
} from '../models';

import { axiosInstance } from '../custom-instance';
import type { ErrorType, BodyType } from '../custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Generate text content using Google GenAI. Credits will be deducted based on token usage.
 * @summary Generate content using AI
 */
export const generateContent = (
  generateContentDto: BodyType<GenerateContentDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/generate`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: generateContentDto,
      signal,
    },
    options
  );
};

export const getGenerateContentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateContent>>,
    TError,
    { data: BodyType<GenerateContentDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateContent>>,
  TError,
  { data: BodyType<GenerateContentDto> },
  TContext
> => {
  const mutationKey = ['generateContent'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateContent>>,
    { data: BodyType<GenerateContentDto> }
  > = (props) => {
    const { data } = props ?? {};

    return generateContent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateContent>>
>;
export type GenerateContentMutationBody = BodyType<GenerateContentDto>;
export type GenerateContentMutationError = ErrorType<void>;

/**
 * @summary Generate content using AI
 */
export const useGenerateContent = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateContent>>,
      TError,
      { data: BodyType<GenerateContentDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof generateContent>>,
  TError,
  { data: BodyType<GenerateContentDto> },
  TContext
> => {
  const mutationOptions = getGenerateContentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get an estimate of credits needed for a given prompt
 * @summary Estimate credit cost for generation
 */
export const estimateCost = (
  params: EstimateCostParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<CostEstimationDto>(
    { url: `/api/genai/cost-estimate`, method: 'GET', params, signal },
    options
  );
};

export const getEstimateCostQueryKey = (params?: EstimateCostParams) => {
  return [`/api/genai/cost-estimate`, ...(params ? [params] : [])] as const;
};

export const getEstimateCostQueryOptions = <
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEstimateCostQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof estimateCost>>> = ({ signal }) =>
    estimateCost(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof estimateCost>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EstimateCostQueryResult = NonNullable<Awaited<ReturnType<typeof estimateCost>>>;
export type EstimateCostQueryError = ErrorType<void>;

export function useEstimateCost<
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof estimateCost>>,
          TError,
          Awaited<ReturnType<typeof estimateCost>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEstimateCost<
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof estimateCost>>,
          TError,
          Awaited<ReturnType<typeof estimateCost>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useEstimateCost<
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Estimate credit cost for generation
 */

export function useEstimateCost<
  TData = Awaited<ReturnType<typeof estimateCost>>,
  TError = ErrorType<void>,
>(
  params: EstimateCostParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof estimateCost>>, TError, TData>>;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getEstimateCostQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return query;
}

/**
 * Propose creative scenarios/ideas based on user prompt. Credits will be deducted based on token usage.
 * @summary Suggest AI generation scenarios
 */
export const suggestScenario = (
  suggestScenarioDto: BodyType<SuggestScenarioDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/suggest-scenario`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: suggestScenarioDto,
      signal,
    },
    options
  );
};

export const getSuggestScenarioMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof suggestScenario>>,
    TError,
    { data: BodyType<SuggestScenarioDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof suggestScenario>>,
  TError,
  { data: BodyType<SuggestScenarioDto> },
  TContext
> => {
  const mutationKey = ['suggestScenario'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof suggestScenario>>,
    { data: BodyType<SuggestScenarioDto> }
  > = (props) => {
    const { data } = props ?? {};

    return suggestScenario(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SuggestScenarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof suggestScenario>>
>;
export type SuggestScenarioMutationBody = BodyType<SuggestScenarioDto>;
export type SuggestScenarioMutationError = ErrorType<void>;

/**
 * @summary Suggest AI generation scenarios
 */
export const useSuggestScenario = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof suggestScenario>>,
      TError,
      { data: BodyType<SuggestScenarioDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof suggestScenario>>,
  TError,
  { data: BodyType<SuggestScenarioDto> },
  TContext
> => {
  const mutationOptions = getSuggestScenarioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Convert audio or video file to text using AI. Supports transcription with custom prompts. Credits will be deducted based on token usage.
 * @summary Convert audio/video to text
 */
export const mediaToText = (
  mediaToTextDto: BodyType<MediaToTextDto>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<GenerationResponseDto>(
    {
      url: `/api/genai/media-to-text`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: mediaToTextDto,
      signal,
    },
    options
  );
};

export const getMediaToTextMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mediaToText>>,
    TError,
    { data: BodyType<MediaToTextDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mediaToText>>,
  TError,
  { data: BodyType<MediaToTextDto> },
  TContext
> => {
  const mutationKey = ['mediaToText'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mediaToText>>,
    { data: BodyType<MediaToTextDto> }
  > = (props) => {
    const { data } = props ?? {};

    return mediaToText(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MediaToTextMutationResult = NonNullable<Awaited<ReturnType<typeof mediaToText>>>;
export type MediaToTextMutationBody = BodyType<MediaToTextDto>;
export type MediaToTextMutationError = ErrorType<void>;

/**
 * @summary Convert audio/video to text
 */
export const useMediaToText = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof mediaToText>>,
      TError,
      { data: BodyType<MediaToTextDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof mediaToText>>,
  TError,
  { data: BodyType<MediaToTextDto> },
  TContext
> => {
  const mutationOptions = getMediaToTextMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
