/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Lyric Atelier API
 * API for Lyric Atelier - AI-powered lyric generation
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { DeleteMedia200, UploadMediaBody, UploadResponseDto } from '../models';

import { axiosInstance } from '../custom-instance';
import type { ErrorType, BodyType } from '../custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Upload an audio or video file to cloud storage. Returns a public URL that can be used with media-to-text API. Max file size: 100MB.
 * @summary Upload media file (audio/video)
 */
export const uploadMedia = (
  uploadMediaBody: BodyType<UploadMediaBody>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  if (uploadMediaBody.file !== undefined) {
    formData.append(`file`, uploadMediaBody.file);
  }

  return axiosInstance<UploadResponseDto>(
    {
      url: `/api/upload/media`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options
  );
};

export const getUploadMediaMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadMedia>>,
    TError,
    { data: BodyType<UploadMediaBody> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadMedia>>,
  TError,
  { data: BodyType<UploadMediaBody> },
  TContext
> => {
  const mutationKey = ['uploadMedia'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadMedia>>,
    { data: BodyType<UploadMediaBody> }
  > = (props) => {
    const { data } = props ?? {};

    return uploadMedia(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadMediaMutationResult = NonNullable<Awaited<ReturnType<typeof uploadMedia>>>;
export type UploadMediaMutationBody = BodyType<UploadMediaBody>;
export type UploadMediaMutationError = ErrorType<void>;

/**
 * @summary Upload media file (audio/video)
 */
export const useUploadMedia = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadMedia>>,
      TError,
      { data: BodyType<UploadMediaBody> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof uploadMedia>>,
  TError,
  { data: BodyType<UploadMediaBody> },
  TContext
> => {
  const mutationOptions = getUploadMediaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete a media file from cloud storage. Provide the full file path (e.g., media/1234567890-song.mp3)
 * @summary Delete media file from storage
 */
export const deleteMedia = (fileName: string, options?: SecondParameter<typeof axiosInstance>) => {
  return axiosInstance<DeleteMedia200>(
    { url: `/api/upload/media/${fileName}`, method: 'DELETE' },
    options
  );
};

export const getDeleteMediaMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMedia>>,
    TError,
    { fileName: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMedia>>,
  TError,
  { fileName: string },
  TContext
> => {
  const mutationKey = ['deleteMedia'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMedia>>,
    { fileName: string }
  > = (props) => {
    const { fileName } = props ?? {};

    return deleteMedia(fileName, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMediaMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMedia>>>;

export type DeleteMediaMutationError = ErrorType<void>;

/**
 * @summary Delete media file from storage
 */
export const useDeleteMedia = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMedia>>,
      TError,
      { fileName: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteMedia>>,
  TError,
  { fileName: string },
  TContext
> => {
  const mutationOptions = getDeleteMediaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
